### ISSUE TITLE
dns dupe test flakey

### ISSUE THREAD

**Issue by arekinath** [joyent/node-cueball#117]

**Comment by melloc** [comment]
For an example, see [this Travis run](https://travis-ci.org/joyent/node-cueball/jobs/269309247):

```
not ok 170 should be equivalent

  ---

    operator: deepEqual

    expected: [ '_foo._tcp.dupe.ok/SRV', '_foo._tcp.dupe.ok/SRV' ]

    actual:   [ '_foo._tcp.dupe.ok/SRV' ]

    at: stage3 [as _onTimeout] (/home/travis/build/joyent/node-cueball/test/dns.test.js:813:5)

    stack: |-

      Error: should be equivalent

          at Test.assert (/home/travis/build/joyent/node-cueball/node_modules/tape/lib/test.js:212:54)

          at Test.bound [as _assert] (/home/travis/build/joyent/node-cueball/node_modules/tape/lib/test.js:64:32)

          at Test.deepEqual.Test.deepEquals.Test.isEquivalent.Test.same (/home/travis/build/joyent/node-cueball/node_modules/tape/lib/test.js:380:10)

          at Test.bound [as deepEqual] (/home/travis/build/joyent/node-cueball/node_modules/tape/lib/test.js:64:32)

          at stage3 [as _onTimeout] (/home/travis/build/joyent/node-cueball/test/dns.test.js:813:5)

          at Timer.listOnTimeout [as ontimeout] (timers.js:121:15)

  ...
```
