### ISSUE TITLE
transient problems in dynamic resolver mode

### ISSUE THREAD

**Issue by arekinath** [joyent/node-cueball#41]
In some SDC deployments, there is only one binder and `/etc/resolv.conf` looks something like:

```
nameserver 192.168.1.11   # binder
nameserver 8.8.8.8
nameserver 8.8.4.4
```

When using dynamic resolver mode with these, with SDC binder, it seems like transient issues at startup are currently possible, like this (from dev staging):

```
[2016-10-21T06:26:48.810Z]  INFO: cloudapi/89096 on c585b5ec-be2d-4943-8e91-a2ed7eaeaced: cueball kang monitor started on port 9091
[2016-10-21T06:26:49.577Z]  INFO: cloudapi/89096 on c585b5ec-be2d-4943-8e91-a2ed7eaeaced: bootstrap shut down
[2016-10-21T06:26:49.578Z]  INFO: cloudapi/89096 on c585b5ec-be2d-4943-8e91-a2ed7eaeaced: cloudapi listening at http://0.0.0.0:8081
[2016-10-21T06:26:49.666Z]  INFO: cloudapi/ufds/89096 on c585b5ec-be2d-4943-8e91-a2ed7eaeaced: LDAP client disconnected
[2016-10-21T06:26:57.700Z]  WARN: CueBallConnectionPool/89096 on c585b5ec-be2d-4943-8e91-a2ed7eaeaced: finished processing (domain=cns.staging-1.joyent.us, service=_http._tcp, pool=84661db3-2219-4335-9249-5fa8c358e3f5)
    VError: failed to find any DNS records for (_http._tcp.)cns.staging-1.joyent.us: first of 2 errors: DNS server failure (SERVFAIL)
        at CueBallDNSResolver.state_process (/opt/smartdc/cloudapi/node_modules/cueball/lib/resolver.js:650:13)
        at CueBallDNSResolver.FSM._gotoState (/opt/smartdc/cloudapi/node_modules/cueball/node_modules/mooremachine/lib/fsm.js:273:4)
        at CueBallDNSResolver.FSM._gotoState (/opt/smartdc/cloudapi/node_modules/cueball/node_modules/mooremachine/lib/fsm.js:300:8)
        at CueBallDNSResolver.FSM._gotoState (/opt/smartdc/cloudapi/node_modules/cueball/node_modules/mooremachine/lib/fsm.js:300:8)
        at FSMStateHandle.gotoState (/opt/smartdc/cloudapi/node_modules/cueball/node_modules/mooremachine/lib/fsm.js:52:23)
        at EventEmitter.<anonymous> (/opt/smartdc/cloudapi/node_modules/cueball/lib/resolver.js:593:5)
        at EventEmitter.emit (events.js:95:17)
        at onLookup (/opt/smartdc/cloudapi/node_modules/cueball/lib/resolver.js:776:7)
        at /opt/smartdc/cloudapi/node_modules/cueball/node_modules/mname-client/lib/client.js:123:6
        at onError (/opt/smartdc/cloudapi/node_modules/cueball/node_modules/mname-client/lib/client.js:177:3)
    Caused by: MultiError: first of 2 errors: DNS server failure (SERVFAIL)
        at new MultiError (/opt/smartdc/cloudapi/node_modules/verror/lib/verror.js:183:9)
        at /opt/smartdc/cloudapi/node_modules/cueball/node_modules/mname-client/lib/client.js:122:14
        at onError (/opt/smartdc/cloudapi/node_modules/cueball/node_modules/mname-client/lib/client.js:177:3)
        at DnsMessage.<anonymous> (/opt/smartdc/cloudapi/node_modules/cueball/node_modules/mname-client/lib/client.js:210:4)
        at DnsMessage.g (events.js:180:16)
        at DnsMessage.emit (events.js:98:17)
        at Socket.<anonymous> (/opt/smartdc/cloudapi/node_modules/cueball/node_modules/mname-client/lib/sockets.js:359:7)
        at Socket.emit (events.js:98:17)
        at UDP.onMessage (dgram.js:441:8)
    Caused by: DnsError: DNS server failure (SERVFAIL)
[2016-10-21T06:26:57.703Z]  WARN: CueBallConnectionPool/89096 on c585b5ec-be2d-4943-8e91-a2ed7eaeaced: underlying resolver failed, moving pool to "failed" state (domain=cns.staging-1.joyent.us, service=_http._tcp, pool=84661db3-2219-4335-9249-5fa8c358e3f5)
[2016-10-21T06:26:57.707Z]  WARN: CueBallConnectionPool/89096 on c585b5ec-be2d-4943-8e91-a2ed7eaeaced: finished processing (domain=mahi.staging-1.joyent.us, service=_http._tcp, pool=0feac787-d3c7-4103-90de-e20c6f72f3a4)
    VError: failed to find any DNS records for (_http._tcp.)mahi.staging-1.joyent.us: first of 2 errors: DNS request type not implemented (NOTIMP)
        at CueBallDNSResolver.state_process (/opt/smartdc/cloudapi/node_modules/cueball/lib/resolver.js:650:13)
        at CueBallDNSResolver.FSM._gotoState (/opt/smartdc/cloudapi/node_modules/cueball/node_modules/mooremachine/lib/fsm.js:273:4)
        at CueBallDNSResolver.FSM._gotoState (/opt/smartdc/cloudapi/node_modules/cueball/node_modules/mooremachine/lib/fsm.js:300:8)
        at CueBallDNSResolver.FSM._gotoState (/opt/smartdc/cloudapi/node_modules/cueball/node_modules/mooremachine/lib/fsm.js:300:8)
        at FSMStateHandle.gotoState (/opt/smartdc/cloudapi/node_modules/cueball/node_modules/mooremachine/lib/fsm.js:52:23)
        at EventEmitter.<anonymous> (/opt/smartdc/cloudapi/node_modules/cueball/lib/resolver.js:593:5)
        at EventEmitter.emit (events.js:95:17)
        at onLookup (/opt/smartdc/cloudapi/node_modules/cueball/lib/resolver.js:776:7)
        at /opt/smartdc/cloudapi/node_modules/cueball/node_modules/mname-client/lib/client.js:123:6
        at onError (/opt/smartdc/cloudapi/node_modules/cueball/node_modules/mname-client/lib/client.js:177:3)
    Caused by: MultiError: first of 2 errors: DNS request type not implemented (NOTIMP)
        at new MultiError (/opt/smartdc/cloudapi/node_modules/verror/lib/verror.js:183:9)
        at /opt/smartdc/cloudapi/node_modules/cueball/node_modules/mname-client/lib/client.js:122:14
        at onError (/opt/smartdc/cloudapi/node_modules/cueball/node_modules/mname-client/lib/client.js:177:3)
        at DnsMessage.<anonymous> (/opt/smartdc/cloudapi/node_modules/cueball/node_modules/mname-client/lib/client.js:210:4)
        at DnsMessage.g (events.js:180:16)
        at DnsMessage.emit (events.js:98:17)
        at Socket.<anonymous> (/opt/smartdc/cloudapi/node_modules/cueball/node_modules/mname-client/lib/sockets.js:359:7)
        at Socket.emit (events.js:98:17)
        at UDP.onMessage (dgram.js:441:8)
    Caused by: DnsError: DNS request type not implemented (NOTIMP)
[2016-10-21T06:26:57.708Z]  WARN: CueBallConnectionPool/89096 on c585b5ec-be2d-4943-8e91-a2ed7eaeaced: underlying resolver failed, moving pool to "failed" state (domain=mahi.staging-1.joyent.us, service=_http._tcp, pool=0feac787-d3c7-4103-90de-e20c6f72f3a4)
[2016-10-21T06:27:57.705Z]  INFO: CueBallConnectionPool/89096 on c585b5ec-be2d-4943-8e91-a2ed7eaeaced: successfully connected to a backend, moving back to running state (domain=cns.staging-1.joyent.us, service=_http._tcp, pool=84661db3-2219-4335-9249-5fa8c358e3f5)
[2016-10-21T06:27:57.708Z]  INFO: CueBallConnectionPool/89096 on c585b5ec-be2d-4943-8e91-a2ed7eaeaced: successfully connected to a backend, moving back to running state (domain=mahi.staging-1.joyent.us, service=_http._tcp, pool=0feac787-d3c7-4103-90de-e20c6f72f3a4)
```

**Comment by arekinath** [comment]
This is solved by #60
