### ISSUE TITLE
rapid add/remove of backend in DNS leads to ConnectionSet crash

### ISSUE THREAD

**Issue by davepacheco** [joyent/node-cueball#47]
Unfortunately, I don't have a core file because this program wasn't configured to dump core.  But I was testing a Moray client (minnow), and twice the program crashed when a new Moray backend was *added* to DNS:

```
{"name":"minnow","hostname":"275dd052-5592-45aa-a371-5cd749dba3b1","pid":3439,"component":"MorayClient","domain":"1.moray.emy-10.joyent.us","key":"1ObkfLk61VF+qH8BEqNI+JJfCJg=.15","level":30,"msg":"removed connection","time":"2016-11-09T18:21:32.651Z","v":0}
{"name":"minnow","hostname":"275dd052-5592-45aa-a371-5cd749dba3b1","pid":3439,"level":50,"err":{"message":"no connections available","name":"NoBackendsError","stack":"NoBackendsError: no connections available\n    at MorayConnectionPool.connAlloc (/opt/smartdc/minnow/node_modules/moray/lib/pool.js:128:17)\n    at MorayClient.ctxCreateForCallback (/opt/smartdc/minnow/node_modules/moray/lib/client.js:756:22)\n    at MorayClient.putObject (/opt/smartdc/minnow/node_modules/moray/lib/client.js:1042:23)\n    at /opt/smartdc/minnow/main.js:220:20\n    at /opt/smartdc/minnow/main.js:189:17"},"msg":"moray: update failed","time":"2016-11-09T18:21:32.777Z","v":0}
{"name":"minnow","hostname":"275dd052-5592-45aa-a371-5cd749dba3b1","pid":3439,"component":"MorayClient","domain":"1.moray.emy-10.joyent.us","key":"1ObkfLk61VF+qH8BEqNI+JJfCJg=.16","level":30,"msg":"new connection","time":"2016-11-09T18:21:34.653Z","v":0}
{"name":"minnow","hostname":"275dd052-5592-45aa-a371-5cd749dba3b1","pid":3439,"component":"MorayClient","domain":"1.moray.emy-10.joyent.us","key":"1ObkfLk61VF+qH8BEqNI+JJfCJg=.16","level":30,"msg":"removed connection","time":"2016-11-09T18:21:34.654Z","v":0}
{"name":"minnow","hostname":"275dd052-5592-45aa-a371-5cd749dba3b1","pid":3439,"component":"MorayClient","domain":"1.moray.emy-10.joyent.us","key":"1ObkfLk61VF+qH8BEqNI+JJfCJg=.17","level":30,"msg":"new connection","time":"2016-11-09T18:21:36.656Z","v":0}
{"name":"minnow","hostname":"275dd052-5592-45aa-a371-5cd749dba3b1","pid":3439,"component":"MorayClient","domain":"1.moray.emy-10.joyent.us","key":"1ObkfLk61VF+qH8BEqNI+JJfCJg=.17","level":30,"msg":"removed connection","time":"2016-11-09T18:21:36.656Z","v":0}

/opt/smartdc/minnow/node_modules/moray/node_modules/cueball/lib/set.js:144
        mod_assert.ok(fsms.length <= 1);
                          ^
TypeError: Cannot read property 'length' of undefined
    at CueBallConnectionSet.on_resolver_removed (/opt/smartdc/minnow/node_modules/moray/node_modules/cueball/lib/set.js:144:20)
    at CueBallResolver.emit (events.js:95:17)
    at CueBallDNSResolver.emit (events.js:95:17)
    at /opt/smartdc/minnow/node_modules/moray/node_modules/cueball/lib/resolver.js:709:8
    at Array.forEach (native)
    at CueBallDNSResolver.state_process (/opt/smartdc/minnow/node_modules/moray/node_modules/cueball/lib/resolver.js:707:10)
    at CueBallDNSResolver.FSM._gotoState (/opt/smartdc/minnow/node_modules/moray/node_modules/cueball/node_modules/mooremachine/lib/fsm.js:273:4)
    at CueBallDNSResolver.FSM._gotoState (/opt/smartdc/minnow/node_modules/moray/node_modules/cueball/node_modules/mooremachine/lib/fsm.js:300:8)
    at FSMStateHandle.gotoState (/opt/smartdc/minnow/node_modules/moray/node_modules/cueball/node_modules/mooremachine/lib/fsm.js:52:23)
    at EventEmitter.<anonymous> (/opt/smartdc/minnow/node_modules/moray/node_modules/cueball/lib/resolver.js:604:5)
```

According to npm, this was cueball 1.1.4, which is the current latest.

**Comment by arekinath** [comment]
This appears to be the same pathology as thoth 3380bc3a2da1e3b9

**Comment by arekinath** [comment]
This occurs when a backend is rapidly added and then removed in DNS. I suspect in the original case that we saw the rapid addition/removal because of binder's zk record caching -- it means that one binder may not answer the same way as another for a brief window of time around when a record is added. This means for a period around a change, cueball may observe the record apparently appearing and disappearing in rapid succession (as it gets answers from different binders each time).

The code in on_resolver_removed should not assume that r_fsms contains the backend in question, because we may not have had it on our list for very long (not even a single turn of the event loop, which would likely fill it out).
