### ISSUE TITLE
pool should never call .close() on a busy backend

### ISSUE THREAD

**Issue by arekinath** [joyent/node-cueball#51]
Currently the if() condition in rebalance() processing removes from the plan can close a 'busy' connection. This should never happen.

**Comment by arekinath** [comment]
This can cause HTTP requests to fail with a "socket hang up" error, when the stack looks like this:
```
    Error: socket hang up
        at createHangUpError (http.js:1535:15)
        at Socket.socketOnEnd (http.js:1631:23)
        at Socket.g (events.js:180:16)
        at Socket.emit (events.js:117:20)
        at _stream_readable.js:944:16
        at process._tickDomainCallback (node.js:502:13)
```
